apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 150Gi
  storageClassName: hostpath-storage
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: spark-role.cloudwalk.com/executor
              operator: In
              values:
                - "true"
  hostPath:
    path: /cloudgpfs/dataforge/ml-studio/yckj4506
    type: DirectoryOrCreate
