apiVersion: batch/v1
kind: Job
metadata:
  name: benchmark-clickhouse-client
spec:
  template:
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      nodeSelector:
        "node-role.kubernetes.io/master=": ""        
      restartPolicy: Never  
      containers:
        - name: benchmark-clickhouse-client
          image: ubuntu:20.04
          command:
            - sh
            - -c
            - |
              cd /cloudgpfs/dataforge/ml-studio/yckj4506/git/bigdata-dev-tools/benchmark/analytical-database/duckdb \
              && sh pipeline.sh
          volumeMounts:
            - name: data
              mountPath: "/cloudgpfs/dataforge/ml-studio"
      volumes:
      - name: data
        hostPath:
          path: "/cloudgpfs/dataforge/ml-studio"              
